title: Kinnaman
baseURL: http://kinnaman.net/
languageCode: en-us
enableRobotsTXT: true
paginate: 10
googleAnalytics: false

params:
  text_color: 
  author: Morgan Kinnaman
  favicon: 
  site_logo: 
  description: Personal website of Morgan Kinnaman. 
  background_color: 
  contact:
    - info: morgan@kinnaman.net
      url: "mailto: morgan@kinnaman.net"
  socialMedia:
    - name: Youtube
      url: https://youtube.com/@morgan_kinnaman
      icon: 
    - name: Github
      url: https://github.com/kinnaman 
      icon: 
    - name: Instagram
      url: https://instagram.com/kinnaman

# All menu urls must have a different assigned weight for ordering.
menu:
  main:
    - identifier: blog
      name: Blog
      title: Blog
      url: /blog/
      weight: 100
    - identifier: about
      name: About
      title: About
      url: /about/
      weight: 200
    - identifier: blips
      name: Blips
      title: Blips - Micro Posts
      url: /blip/
      weight: 300
       #  footer: true

sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml

module:
  mounts:
    - source: node_modules/bootstrap/dist/js/bootstrap.bundle.min.js
      target: assets/js/bootstrap.bundle.min.js
    - source: node_modules/bootstrap/dist/js/bootstrap.bundle.min.js
      target: assets/js/bootstrap.bundle.min.js

theme: 'simplesite'
